## NumPy Notebook

In [2]:
import numpy as np

In [4]:
nums = [1,2,3,4]
arr = np.array(nums)
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr*2

array([2, 4, 6, 8])

In [7]:
arr**4

array([  1,  16,  81, 256], dtype=int32)

In [10]:
arr = np.arange(0,10,2.5) ## How many nos will be generated
arr

array([0. , 2.5, 5. , 7.5])

In [12]:
arr = np.linspace(0,10,6) # how many no. you want in the range
arr

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
array = np.zeros((3,4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
array.shape

(3, 4)

In [18]:
arr = np.ones((3,4))*10
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [27]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
I.dtype

dtype('float64')

In [29]:
I.astype('int8')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)