# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(0,11)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
#Get a value at an index
arr[8]

8

In [6]:
#Get values in a range
arr[1:5]  # elements 2 to 5

array([1, 2, 3, 4])

In [7]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
#Setting a value with index range (Broadcasting)
arr[:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [20]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[0:5] = 200
arr_copy

array([200, 200, 200, 200, 200,  99,   6,   7,   8,   9,  10])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [16]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [17]:
# Getting individual element value
arr_2d[1,0]

20

In [18]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [21]:
#Set up matrix
arr2d = np.zeros((10,10))

In [22]:
#Length of array
arr_length = arr2d.shape[1]

In [23]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [24]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
x = 2
arr[arr>x]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Row, Col index

In [45]:
arr = np.random.rand(5,5)
arr

array([[0.05673126, 0.64102508, 0.45477084, 0.7675351 , 0.62904955],
       [0.98120265, 0.89468983, 0.14681754, 0.30048261, 0.00129618],
       [0.19274665, 0.19033108, 0.83400721, 0.18492423, 0.30029613],
       [0.65006068, 0.21395159, 0.20182738, 0.81984166, 0.92736735],
       [0.49927651, 0.8614508 , 0.03264064, 0.5409793 , 0.165056  ]])

In [46]:
arr[-1]

array([0.49927651, 0.8614508 , 0.03264064, 0.5409793 , 0.165056  ])

In [47]:
arr[:3,-1]

array([0.62904955, 0.00129618, 0.30029613])

In [48]:
arr

array([[0.05673126, 0.64102508, 0.45477084, 0.7675351 , 0.62904955],
       [0.98120265, 0.89468983, 0.14681754, 0.30048261, 0.00129618],
       [0.19274665, 0.19033108, 0.83400721, 0.18492423, 0.30029613],
       [0.65006068, 0.21395159, 0.20182738, 0.81984166, 0.92736735],
       [0.49927651, 0.8614508 , 0.03264064, 0.5409793 , 0.165056  ]])

In [49]:
arr.diagonal()

array([0.05673126, 0.89468983, 0.83400721, 0.81984166, 0.165056  ])

In [55]:
arr.T

array([[0.05673126, 0.98120265, 0.19274665, 0.65006068, 0.49927651],
       [0.64102508, 0.89468983, 0.19033108, 0.21395159, 0.8614508 ],
       [0.45477084, 0.14681754, 0.83400721, 0.20182738, 0.03264064],
       [0.7675351 , 0.30048261, 0.18492423, 0.81984166, 0.5409793 ],
       [0.62904955, 0.00129618, 0.30029613, 0.92736735, 0.165056  ]])

In [51]:
arr.sum()

11.488357882411725

In [52]:
arr.std()

0.3129500483156829

In [53]:
arr.mean()

0.459534315296469

In [60]:
arr.cumsum()

array([ 0.05673126,  0.69775634,  1.15252718,  1.92006228,  2.54911184,
        3.53031449,  4.42500432,  4.57182187,  4.87230448,  4.87360066,
        5.06634731,  5.25667839,  6.0906856 ,  6.27560983,  6.57590596,
        7.22596664,  7.43991823,  7.64174561,  8.46158727,  9.38895462,
        9.88823113, 10.74968193, 10.78232257, 11.32330188, 11.48835788])